"""initial schema (baseline 2026)

Revision ID: dbd5fe7ee652
Revises: 
Create Date: 2026-09-15 20:25:09.600871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbd5fe7ee652'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('processing_key', sa.String(), nullable=True),
    sa.Column('abn', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('entity_count', sa.Integer(), nullable=True),
    sa.Column('red_flag_count', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pipeline_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pipeline_runs_abn'), ['abn'], unique=False)
        batch_op.create_index(batch_op.f('ix_pipeline_runs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pipeline_runs_processing_key'), ['processing_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_pipeline_runs_run_id'), ['run_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_pipeline_runs_status'), ['status'], unique=False)

    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenants_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenants_name'), ['name'], unique=True)

    op.create_table('trusts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('processing_key', sa.String(), nullable=True),
    sa.Column('reference_number', sa.String(), nullable=True),
    sa.Column('abn', sa.String(), nullable=False),
    sa.Column('trust_name', sa.String(), nullable=True),
    sa.Column('trustee_company', sa.String(), nullable=True),
    sa.Column('is_high_risk', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trusts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trusts_abn'), ['abn'], unique=False)
        batch_op.create_index(batch_op.f('ix_trusts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trusts_processing_key'), ['processing_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_trusts_reference_number'), ['reference_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_trusts_run_id'), ['run_id'], unique=True)

    op.create_table('analysis_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('abn', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('compliance_memo', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_jobs_abn'), ['abn'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_jobs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_jobs_run_id'), ['run_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_analysis_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_jobs_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('key_prefix', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_key_hash'), ['key_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_api_keys_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('beneficiaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trust_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_corporate', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['trust_id'], ['trusts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('beneficiaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_beneficiaries_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_beneficiaries_name'), ['name'], unique=False)

    op.create_table('compliance_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trust_id', sa.Integer(), nullable=True),
    sa.Column('report_text', sa.String(), nullable=True),
    sa.Column('s3_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['trust_id'], ['trusts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compliance_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compliance_reports_id'), ['id'], unique=False)

    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_name', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('source_trust_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['source_trust_id'], ['trusts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entities_canonical_name'), ['canonical_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_entities_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_entities_id'), ['id'], unique=False)

    op.create_table('red_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trust_id', sa.Integer(), nullable=True),
    sa.Column('extracted_name', sa.String(), nullable=True),
    sa.Column('watchlist_name', sa.String(), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('action_required', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['trust_id'], ['trusts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('red_flags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_red_flags_extracted_name'), ['extracted_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_red_flags_id'), ['id'], unique=False)

    op.create_table('entity_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('alias_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entity_aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entity_aliases_alias'), ['alias'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_aliases_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_aliases_id'), ['id'], unique=False)

    op.create_table('screening_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('watchlist_name', sa.String(), nullable=True),
    sa.Column('watchlist_type', sa.String(), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('match_method', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('screening_matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_screening_matches_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_screening_matches_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_screening_matches_match_method'), ['match_method'], unique=False)
        batch_op.create_index(batch_op.f('ix_screening_matches_watchlist_name'), ['watchlist_name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('screening_matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_screening_matches_watchlist_name'))
        batch_op.drop_index(batch_op.f('ix_screening_matches_match_method'))
        batch_op.drop_index(batch_op.f('ix_screening_matches_id'))
        batch_op.drop_index(batch_op.f('ix_screening_matches_entity_id'))

    op.drop_table('screening_matches')
    with op.batch_alter_table('entity_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entity_aliases_id'))
        batch_op.drop_index(batch_op.f('ix_entity_aliases_entity_id'))
        batch_op.drop_index(batch_op.f('ix_entity_aliases_alias'))

    op.drop_table('entity_aliases')
    with op.batch_alter_table('red_flags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_red_flags_id'))
        batch_op.drop_index(batch_op.f('ix_red_flags_extracted_name'))

    op.drop_table('red_flags')
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entities_id'))
        batch_op.drop_index(batch_op.f('ix_entities_entity_type'))
        batch_op.drop_index(batch_op.f('ix_entities_canonical_name'))

    op.drop_table('entities')
    with op.batch_alter_table('compliance_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compliance_reports_id'))

    op.drop_table('compliance_reports')
    with op.batch_alter_table('beneficiaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_beneficiaries_name'))
        batch_op.drop_index(batch_op.f('ix_beneficiaries_id'))

    op.drop_table('beneficiaries')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_api_keys_key_hash'))
        batch_op.drop_index(batch_op.f('ix_api_keys_id'))

    op.drop_table('api_keys')
    with op.batch_alter_table('analysis_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_jobs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_analysis_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_analysis_jobs_run_id'))
        batch_op.drop_index(batch_op.f('ix_analysis_jobs_id'))
        batch_op.drop_index(batch_op.f('ix_analysis_jobs_abn'))

    op.drop_table('analysis_jobs')
    with op.batch_alter_table('trusts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trusts_run_id'))
        batch_op.drop_index(batch_op.f('ix_trusts_reference_number'))
        batch_op.drop_index(batch_op.f('ix_trusts_processing_key'))
        batch_op.drop_index(batch_op.f('ix_trusts_id'))
        batch_op.drop_index(batch_op.f('ix_trusts_abn'))

    op.drop_table('trusts')
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenants_name'))
        batch_op.drop_index(batch_op.f('ix_tenants_id'))

    op.drop_table('tenants')
    with op.batch_alter_table('pipeline_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pipeline_runs_status'))
        batch_op.drop_index(batch_op.f('ix_pipeline_runs_run_id'))
        batch_op.drop_index(batch_op.f('ix_pipeline_runs_processing_key'))
        batch_op.drop_index(batch_op.f('ix_pipeline_runs_id'))
        batch_op.drop_index(batch_op.f('ix_pipeline_runs_abn'))

    op.drop_table('pipeline_runs')
    # ### end Alembic commands ###
